[package]
name = "snuffles"
version = "0.2.0"
edition = "2024"
description = "A very low-quality graphics API that I use myself for making graphs and visualizations quickly, where I need perf"
license = "MIT"

[dependencies]
cgmath = "0.18"
wgpu = "28"
pollster = "0.4"
winit = "0.30"
image = "0.25"

